---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-ubuntu-desktop
description: Install ubuntu-desktop through ansible
tags:
  - ansible
  - ansible-role
  - ubuntu
  - ubuntu-desktop
github:
  has_issues: true
  has_projects: false
  has_wiki: false
