---
- name: uninstall display manager
  apt:
    name: "{{ boxes_ubuntu_desktop_displaymanager_uninstall }}"
    state: absent
  loop_control:
    loop_var: boxes_ubuntu_desktop_displaymanager_uninstall
  loop:
    - lightdm

- name: install display manager
  apt:
    name: "{{ boxes_ubuntu_desktop_displaymanager_install }}"
    state: present
  loop_control:
    loop_var: boxes_ubuntu_desktop_displaymanager_install
  loop:
    - gdm3
