---
- name: install gnome
  apt:
    name: "{{ boxes_ubuntu_desktop_package_name }}"
    state: present
    install_recommends: false
  loop_control:
    loop_var: boxes_ubuntu_desktop_package_name
  loop:
    - ubuntu-gnome-desktop
    # - libxss1
